### ISSUE TITLE
Čitelné barvy výsledkovek

### ISSUE THREAD

**Issue by Werkov** [fykosak/online-contest#3]
Pocet bodov 0 / ratio-0 bol biely na bielom (ma
vobec existovat?). Okrem toho som si vsimol ze ratio-2 a ratio-3 su
prakticky rovnake a ratio-4 existuje, ale nie je pouzivane. Navrhujem tieto
zmeny do css (momentalne je to v bootstrap.min.:
ratio-5: #180
ratio-3: #392
ratio-2: #4b4
ratio-1: #4d4
ratio-0: #7ea (alebo zaistit ze sa neobjavi)
S tymito farbami mi pride ratio velmi dobre vycitatelne (5,3,2,1,0 = prepe,
trava, sedsia zelena, jasnozelena, utopenec) aj bez porovnavania.

Cc: @0Xellos

**Comment by 0Xellos** [comment]
Done.
