### ISSUE TITLE
Second page of answer history yields HTTP error 500

### ISSUE THREAD

**Issue by Werkov** [fykosak/online-contest#8]
https://github.com/fykosak/online-contest/blob/master/app/FrontendModule/components/BaseListComponent.php#L51

Source is initialized only in render stage, should be in action.

Reproducible on 4c36060165ae9fb0b2b39e1b0a5c2a0526552be7.

**Comment by timkol** [comment]
@Werkov Thanks for identifying the problem.

**Comment by Werkov** [comment]
And I thank for the commit. Don't be afraid of referencing the issue number in the commit message. 
Fixed in 7c81ef51ceaab18124975a3c3a95b18d37fad022. (I wonder if backwards reference works.)
